#include "KeyboardKeyHelper.h"
#include <dinput.h>

namespace inputs
{

uint64_t ToDirectKeyboardKey(const KeyboardKey i_keyboardKey)
{
	switch (i_keyboardKey)
	{
	case KeyboardKey::Escape:
		return DIK_ESCAPE;
	case KeyboardKey::N1:
		return DIK_1;
	case KeyboardKey::N2:
		return DIK_2;
	case KeyboardKey::N3:
		return DIK_3;
	case KeyboardKey::N4:
		return DIK_4;
	case KeyboardKey::N5:
		return DIK_5;
	case KeyboardKey::N6:
		return DIK_6;
	case KeyboardKey::N7:
		return DIK_7;
	case KeyboardKey::N8:
		return DIK_8;
	case KeyboardKey::N9:
		return DIK_9;
	case KeyboardKey::N0:
		return DIK_0;
	case KeyboardKey::Minus:
		return DIK_MINUS;
	case KeyboardKey::Equals:
		return DIK_EQUALS;
	case KeyboardKey::Back:
		return DIK_BACK;
	case KeyboardKey::Tab:
		return DIK_TAB;
	case KeyboardKey::Q:
		return DIK_Q;
	case KeyboardKey::W:
		return DIK_W;
	case KeyboardKey::E:
		return DIK_E;
	case KeyboardKey::R:
		return DIK_R;
	case KeyboardKey::T:
		return DIK_T;
	case KeyboardKey::Y:
		return DIK_Y;
	case KeyboardKey::U:
		return DIK_U;
	case KeyboardKey::I:
		return DIK_I;
	case KeyboardKey::O:
		return DIK_O;
	case KeyboardKey::P:
		return DIK_P;
	case KeyboardKey::LeftBracket:
		return DIK_LBRACKET;
	case KeyboardKey::RightBracket:
		return DIK_RBRACKET;
	case KeyboardKey::Return:
		return DIK_RETURN;
	case KeyboardKey::LeftControl:
		return DIK_LCONTROL;
	case KeyboardKey::A:
		return DIK_A;
	case KeyboardKey::S:
		return DIK_S;
	case KeyboardKey::D:
		return DIK_D;
	case KeyboardKey::F:
		return DIK_F;
	case KeyboardKey::G:
		return DIK_G;
	case KeyboardKey::H:
		return DIK_H;
	case KeyboardKey::J:
		return DIK_J;
	case KeyboardKey::K:
		return DIK_K;
	case KeyboardKey::L:
		return DIK_L;
	case KeyboardKey::Semicolon:
		return DIK_SEMICOLON;
	case KeyboardKey::Apostrophe:
		return DIK_APOSTROPHE;
	case KeyboardKey::Grave:
		return DIK_GRAVE;
	case KeyboardKey::LeftShift:
		return DIK_LSHIFT;
	case KeyboardKey::Backlash:
		return DIK_BACKSLASH;
	case KeyboardKey::Z:
		return DIK_Z;
	case KeyboardKey::X:
		return DIK_X;
	case KeyboardKey::C:
		return DIK_C;
	case KeyboardKey::V:
		return DIK_V;
	case KeyboardKey::B:
		return DIK_B;
	case KeyboardKey::N:
		return DIK_N;
	case KeyboardKey::M:
		return DIK_M;
	case KeyboardKey::Coma:
		return DIK_COMMA;
	case KeyboardKey::Period:
		return DIK_PERIOD;
	case KeyboardKey::Slash:
		return DIK_SLASH;
	case KeyboardKey::RightShift:
		return DIK_RSHIFT;
	case KeyboardKey::Multiply:
		return DIK_MULTIPLY;
	case KeyboardKey::LeftAlt:
		return DIK_LALT;
	case KeyboardKey::Space:
		return DIK_SPACE;
	case KeyboardKey::Capital:
		return DIK_CAPITAL;
	case KeyboardKey::F1:
		return DIK_F1;
	case KeyboardKey::F2:
		return DIK_F2;
	case KeyboardKey::F3:
		return DIK_F3;
	case KeyboardKey::F4:
		return DIK_F4;
	case KeyboardKey::F5:
		return DIK_F5;
	case KeyboardKey::F6:
		return DIK_F6;
	case KeyboardKey::F7:
		return DIK_F7;
	case KeyboardKey::F8:
		return DIK_F8;
	case KeyboardKey::F9:
		return DIK_F9;
	case KeyboardKey::F10:
		return DIK_F10;
	case KeyboardKey::Numlock:
		return DIK_NUMLOCK;
	case KeyboardKey::Scroll:
		return DIK_SCROLL;
	case KeyboardKey::Numpad7:
		return DIK_NUMPAD7;
	case KeyboardKey::Numpad8:
		return DIK_NUMPAD8;
	case KeyboardKey::Numpad9:
		return DIK_NUMPAD9;
	case KeyboardKey::Subtract:
		return DIK_SUBTRACT;
	case KeyboardKey::Numpad4:
		return DIK_NUMPAD4;
	case KeyboardKey::Numpad5:
		return DIK_NUMPAD5;
	case KeyboardKey::Numpad6:
		return DIK_NUMPAD6;
	case KeyboardKey::Add:
		return DIK_ADD;
	case KeyboardKey::Numpad1:
		return DIK_NUMPAD1;
	case KeyboardKey::Numpad2:
		return DIK_NUMPAD2;
	case KeyboardKey::Numpad3:
		return DIK_NUMPAD3;
	case KeyboardKey::Numpad0:
		return DIK_NUMPAD0;
	case KeyboardKey::Decimal:
		return DIK_DECIMAL;
	case KeyboardKey::Oem102:
		return DIK_OEM_102;
	case KeyboardKey::F11:
		return DIK_F11;
	case KeyboardKey::F12:
		return DIK_F12;
	case KeyboardKey::F13:
		return DIK_F13;
	case KeyboardKey::F14:
		return DIK_F14;
	case KeyboardKey::F15:
		return DIK_F15;
	case KeyboardKey::Kana:
		return DIK_KANA;
	case KeyboardKey::AbntC1:
		return DIK_ABNT_C1;
	case KeyboardKey::Convert:
		return DIK_CONVERT;
	case KeyboardKey::NoConvert:
		return DIK_NOCONVERT;
	case KeyboardKey::Yen:
		return DIK_YEN;
	case KeyboardKey::AbntC2:
		return DIK_ABNT_C2;
	case KeyboardKey::NumpadEquals:
		return DIK_NUMPADEQUALS;
	case KeyboardKey::PrevTrack:
		return DIK_PREVTRACK;
	case KeyboardKey::At:
		return DIK_AT;
	case KeyboardKey::Colon:
		return DIK_COLON;
	case KeyboardKey::Underline:
		return DIK_UNDERLINE;
	case KeyboardKey::Kanji:
		return DIK_KANJI;
	case KeyboardKey::Stop:
		return DIK_STOP;
	case KeyboardKey::Ax:
		return DIK_AX;
	case KeyboardKey::Unlabeled:
		return DIK_UNLABELED;
	case KeyboardKey::NextTrack:
		return DIK_NEXTTRACK;
	case KeyboardKey::NumpadEnter:
		return DIK_NUMPADENTER;
	case KeyboardKey::RightControl:
		return DIK_RCONTROL;
	case KeyboardKey::Mute:
		return DIK_MUTE;
	case KeyboardKey::Calculator:
		return DIK_CALCULATOR;
	case KeyboardKey::PlayPause:
		return DIK_PLAYPAUSE;
	case KeyboardKey::MediaStop:
		return DIK_MEDIASTOP;
	case KeyboardKey::VolumeDown:
		return DIK_VOLUMEDOWN;
	case KeyboardKey::VolumeUp:
		return DIK_VOLUMEUP;
	case KeyboardKey::WebHome:
		return DIK_WEBHOME;
	case KeyboardKey::NumpadComma:
		return DIK_NUMPADCOMMA;
	case KeyboardKey::Divide:
		return DIK_DIVIDE;
	case KeyboardKey::SysRQ:
		return DIK_SYSRQ;
	case KeyboardKey::RightAlt:
		return DIK_RALT;
	case KeyboardKey::Pause:
		return DIK_PAUSE;
	case KeyboardKey::Home:
		return DIK_HOME;
	case KeyboardKey::Up:
		return DIK_UP;
	case KeyboardKey::Prior:
		return DIK_PRIOR;
	case KeyboardKey::Left:
		return DIK_LEFT;
	case KeyboardKey::Right:
		return DIK_RIGHT;
	case KeyboardKey::End:
		return DIK_END;
	case KeyboardKey::Down:
		return DIK_DOWN;
	case KeyboardKey::Next:
		return DIK_NEXT;
	case KeyboardKey::Insert:
		return DIK_INSERT;
	case KeyboardKey::Delete:
		return DIK_DELETE;
	case KeyboardKey::LeftWin:
		return DIK_LWIN;
	case KeyboardKey::RightWin:
		return DIK_RWIN;
	case KeyboardKey::Apps:
		return DIK_APPS;
	case KeyboardKey::Power:
		return DIK_POWER;
	case KeyboardKey::Sleep:
		return DIK_SLEEP;
	case KeyboardKey::Wake:
		return DIK_WAKE;
	case KeyboardKey::WebSearch:
		return DIK_WEBSEARCH;
	case KeyboardKey::WebFavorite:
		return DIK_WEBFAVORITES;
	case KeyboardKey::WebRefresh:
		return DIK_WEBREFRESH;
	case KeyboardKey::WebStop:
		return DIK_WEBSTOP;
	case KeyboardKey::WebForward:
		return DIK_WEBFORWARD;
	case KeyboardKey::WebBack:
		return DIK_WEBBACK;
	case KeyboardKey::MyComputer:
		return DIK_MYCOMPUTER;
	case KeyboardKey::Mail:
		return DIK_MAIL;
	case KeyboardKey::MediaSelect:
		return DIK_MEDIASELECT;
	}
}

KeyboardKey ToKeyboardKey(const uint64_t i_directKey)
{
	switch (i_directKey)
	{
	case DIK_ESCAPE:
		return KeyboardKey::Escape;
	case DIK_1:
		return KeyboardKey::N1;
	case DIK_2:
		return KeyboardKey::N2;
	case DIK_3:
		return KeyboardKey::N3;
	case DIK_4:
		return KeyboardKey::N4;
	case DIK_5:
		return KeyboardKey::N5;
	case DIK_6:
		return KeyboardKey::N6;
	case DIK_7:
		return KeyboardKey::N7;
	case DIK_8:
		return KeyboardKey::N8;
	case DIK_9:
		return KeyboardKey::N9;
	case DIK_0:
		return KeyboardKey::N0;
	case DIK_MINUS:
		return KeyboardKey::Minus;
	case DIK_EQUALS:
		return KeyboardKey::Equals;
	case DIK_BACK:
		return KeyboardKey::Back;
	case DIK_TAB:
		return KeyboardKey::Tab;
	case DIK_Q:
		return KeyboardKey::Q;
	case DIK_W:
		return KeyboardKey::W;
	case DIK_E:
		return KeyboardKey::E;
	case DIK_R:
		return KeyboardKey::R;
	case DIK_T:
		return KeyboardKey::T;
	case DIK_Y:
		return KeyboardKey::Y;
	case DIK_U:
		return KeyboardKey::U;
	case DIK_I:
		return KeyboardKey::I;
	case DIK_O:
		return KeyboardKey::O;
	case DIK_P:
		return KeyboardKey::P;
	case DIK_LBRACKET:
		return KeyboardKey::LeftBracket;
	case DIK_RBRACKET:
		return KeyboardKey::RightBracket;
	case DIK_RETURN:
		return KeyboardKey::Return;
	case DIK_LCONTROL:
		return KeyboardKey::LeftControl;
	case DIK_A:
		return KeyboardKey::A;
	case DIK_S:
		return KeyboardKey::S;
	case DIK_D:
		return KeyboardKey::D;
	case DIK_F:
		return KeyboardKey::F;
	case DIK_G:
		return KeyboardKey::G;
	case DIK_H:
		return KeyboardKey::H;
	case DIK_J:
		return KeyboardKey::J;
	case DIK_K:
		return KeyboardKey::K;
	case DIK_L:
		return KeyboardKey::L;
	case DIK_SEMICOLON:
		return KeyboardKey::Semicolon;
	case DIK_APOSTROPHE:
		return KeyboardKey::Apostrophe;
	case DIK_GRAVE:
		return KeyboardKey::Grave;
	case DIK_LSHIFT:
		return KeyboardKey::LeftShift;
	case DIK_BACKSLASH:
		return KeyboardKey::Backlash;
	case DIK_Z:
		return KeyboardKey::Z;
	case DIK_X:
		return KeyboardKey::X;
	case DIK_C:
		return KeyboardKey::C;
	case DIK_V:
		return KeyboardKey::V;
	case DIK_B:
		return KeyboardKey::B;
	case DIK_N:
		return KeyboardKey::N;
	case DIK_M:
		return KeyboardKey::M;
	case DIK_COMMA:
		return KeyboardKey::Coma;
	case DIK_PERIOD:
		return KeyboardKey::Period;
	case DIK_SLASH:
		return KeyboardKey::Slash;
	case DIK_RSHIFT:
		return KeyboardKey::RightShift;
	case DIK_MULTIPLY:
		return KeyboardKey::Multiply;
	case DIK_LALT:
		return KeyboardKey::LeftAlt;
	case DIK_SPACE:
		return KeyboardKey::Space;
	case DIK_CAPITAL:
		return KeyboardKey::Capital;
	case DIK_F1:
		return KeyboardKey::F1;
	case DIK_F2:
		return KeyboardKey::F2;
	case DIK_F3:
		return KeyboardKey::F3;
	case DIK_F4:
		return KeyboardKey::F4;
	case DIK_F5:
		return KeyboardKey::F5;
	case DIK_F6:
		return KeyboardKey::F6;
	case DIK_F7:
		return KeyboardKey::F7;
	case DIK_F8:
		return KeyboardKey::F8;
	case DIK_F9:
		return KeyboardKey::F9;
	case DIK_F10:
		return KeyboardKey::F10;
	case DIK_NUMLOCK:
		return KeyboardKey::Numlock;
	case DIK_SCROLL:
		return KeyboardKey::Scroll;
	case DIK_NUMPAD7:
		return KeyboardKey::Numpad7;
	case DIK_NUMPAD8:
		return KeyboardKey::Numpad8;
	case DIK_NUMPAD9:
		return KeyboardKey::Numpad9;
	case DIK_SUBTRACT:
		return KeyboardKey::Subtract;
	case DIK_NUMPAD4:
		return KeyboardKey::Numpad4;
	case DIK_NUMPAD5:
		return KeyboardKey::Numpad5;
	case DIK_NUMPAD6:
		return KeyboardKey::Numpad6;
	case DIK_ADD:
		return KeyboardKey::Add;
	case DIK_NUMPAD1:
		return KeyboardKey::Numpad1;
	case DIK_NUMPAD2:
		return KeyboardKey::Numpad2;
	case DIK_NUMPAD3:
		return KeyboardKey::Numpad3;
	case DIK_NUMPAD0:
		return KeyboardKey::Numpad0;
	case DIK_DECIMAL:
		return KeyboardKey::Decimal;
	case DIK_OEM_102:
		return KeyboardKey::Oem102;
	case DIK_F11:
		return KeyboardKey::F11;
	case DIK_F12:
		return KeyboardKey::F12;
	case DIK_F13:
		return KeyboardKey::F13;
	case DIK_F14:
		return KeyboardKey::F14;
	case DIK_F15:
		return KeyboardKey::F15;
	case DIK_KANA:
		return KeyboardKey::Kana;
	case DIK_ABNT_C1:
		return KeyboardKey::AbntC1;
	case DIK_CONVERT:
		return KeyboardKey::Convert;
	case DIK_NOCONVERT:
		return KeyboardKey::NoConvert;
	case DIK_YEN:
		return KeyboardKey::Yen;
	case DIK_ABNT_C2:
		return KeyboardKey::AbntC2;
	case DIK_NUMPADEQUALS:
		return KeyboardKey::NumpadEquals;
	case DIK_PREVTRACK:
		return KeyboardKey::PrevTrack;
	case DIK_AT:
		return KeyboardKey::At;
	case DIK_COLON:
		return KeyboardKey::Colon;
	case DIK_UNDERLINE:
		return KeyboardKey::Underline;
	case DIK_KANJI:
		return KeyboardKey::Kanji;
	case DIK_STOP:
		return KeyboardKey::Stop;
	case DIK_AX:
		return KeyboardKey::Ax;
	case DIK_UNLABELED:
		return KeyboardKey::Unlabeled;
	case DIK_NEXTTRACK:
		return KeyboardKey::NextTrack;
	case DIK_NUMPADENTER:
		return KeyboardKey::NumpadEnter;
	case DIK_RCONTROL:
		return KeyboardKey::RightControl;
	case DIK_MUTE:
		return KeyboardKey::Mute;
	case DIK_CALCULATOR:
		return KeyboardKey::Calculator;
	case DIK_PLAYPAUSE:
		return KeyboardKey::PlayPause;
	case DIK_MEDIASTOP:
		return KeyboardKey::MediaStop;
	case DIK_VOLUMEDOWN:
		return KeyboardKey::VolumeDown;
	case DIK_VOLUMEUP:
		return KeyboardKey::VolumeUp;
	case DIK_WEBHOME:
		return KeyboardKey::WebHome;
	case DIK_NUMPADCOMMA:
		return KeyboardKey::NumpadComma;
	case DIK_DIVIDE:
		return KeyboardKey::Divide;
	case DIK_SYSRQ:
		return KeyboardKey::SysRQ;
	case DIK_RALT:
		return KeyboardKey::RightAlt;
	case DIK_PAUSE:
		return KeyboardKey::Pause;
	case DIK_HOME:
		return KeyboardKey::Home;
	case DIK_UP:
		return KeyboardKey::Up;
	case DIK_PRIOR:
		return KeyboardKey::Prior;
	case DIK_LEFT:
		return KeyboardKey::Left;
	case DIK_RIGHT:
		return KeyboardKey::Right;
	case DIK_END:
		return KeyboardKey::End;
	case DIK_DOWN:
		return KeyboardKey::Down;
	case DIK_NEXT:
		return KeyboardKey::Next;
	case DIK_INSERT:
		return KeyboardKey::Insert;
	case DIK_DELETE:
		return KeyboardKey::Delete;
	case DIK_LWIN:
		return KeyboardKey::LeftWin;
	case DIK_RWIN:
		return KeyboardKey::RightWin;
	case DIK_APPS:
		return KeyboardKey::Apps;
	case DIK_POWER:
		return KeyboardKey::Power;
	case DIK_SLEEP:
		return KeyboardKey::Sleep;
	case DIK_WAKE:
		return KeyboardKey::Wake;
	case DIK_WEBSEARCH:
		return KeyboardKey::WebSearch;
	case DIK_WEBFAVORITES:
		return KeyboardKey::WebFavorite;
	case DIK_WEBREFRESH:
		return KeyboardKey::WebRefresh;
	case DIK_WEBSTOP:
		return KeyboardKey::WebStop;
	case DIK_WEBFORWARD:
		return KeyboardKey::WebForward;
	case DIK_WEBBACK:
		return KeyboardKey::WebBack;
	case DIK_MYCOMPUTER:
		return KeyboardKey::MyComputer;
	case DIK_MAIL:
		return KeyboardKey::Mail;
	case DIK_MEDIASELECT:
		return KeyboardKey::MediaSelect;
	}
}

} // namespace inputs
