#pragma once
#include <cstdint>

namespace core
{

enum class AnimationId : uint64_t
{
	SophiaWheelMoveLeft,
	SophiaWheelMoveRight,
	SophiaGunLeftMoveUp,
	SophiaGunRightMoveUp,
	SophiaHeadLeftMoveUp,
	SophiaHeadRightMoveUp,
	SophiaHeadEjectJasonLeft,
	SophiaHeadEjectJasonRight,
	JasonWalkLeft,
	JasonWalkRight,
	JasonClimb,
	JasonCrawlLeft,
	JasonCrawlRight,
	JasonFall,
	JasonTopDownWalkDown,
	JasonTopDownWalkLeft,
	JasonTopDownWalkUp,
	JasonTopDownWalkRight,
	BigExplosion,
	MediumExplosion,
	SmallExplosion,
	WormMoveLeft,
	WormMoveRight,
	DomeUpMoveLeft,
	DomeUpMoveRight,
	DomeDownMoveLeft,
	DomeDownMoveRight,
	DomeLeftMoveUp,
	DomeLeftMoveDown,
	DomeRightMoveUp,
	DomeRightMoveDown,
	JumperMoveLeft,
	JumperMoveRight,
	Orb,
	Walker,
	SkullMoveLeft,
	SkullMoveRight,
	Floater,
	InsectMoveLeft,
	InsectMoveRight,
	DasherIdle,
	DasherMove,
	HeadLeft,
	HeadRight,
	SpiralLeft,
	SpiralRight,
	TeleporterLeft,
	TeleporterRight,
	Eyeball,
	Cannon,
	BossHead,
	Opening,
	Rollout,
	COUNT // Special enum
};

} // namespace core