#pragma once
#include <cstdint>

namespace ids
{

enum class SpriteId : uint64_t
{
#pragma region Sophia
	SophiaGunLeft,
	SophiaGunRight,
	SophiaGunUpleft,
	SophiaGunUpright,
	SophiaGunUp,
	SophiaHeadLeft,
	SophiaHeadRight,
	SophiaHeadUpLeft,
	SophiaHeadUpRight,
	SophiaBody,
	SophiaBodyUpRight,
	SophiaBodyUpLeft,
	SophiaHeadEjectJasonLeft1,
	SophiaHeadEjectJasonLeft2,
	SophiaHeadEjectJasonRight1,
	SophiaHeadEjectJasonRight2,
	SophiaGunLeftWhite,
	SophiaGunRightWhite,
	SophiaGunUpLeftWhite,
	SophiaGunUpRightWhite,
	SophiaGunUpWhite,
	SophiaHeadLeftWhite,
	SophiaHeadRightWhite,
	SophiaHeadUpLeftWhite,
	SophiaHeadUpRightWhite,
	SophiaBodyWhite,
	SophiaBodyUpRightWhite,
	SophiaBodyUpLeftWhite,
	SophiaWheel1,
	SophiaWheel2,
	SophiaWheel3,
	SophiaWheel4,
	SophiaWheel5,
	SophiaWheel6,
	SophiaWheel7,
	SophiaWheel8,
	SophiaBulletLeft,
	SophiaBulletRight,
	SophiaBulletUp,
	SophiaMissileHeadLeft,
	SophiaMissileHeadUp,
	SophiaMissileHeadRight,
	SophiaMissileHeadDown,
	SophiaMissileTailLeft,
	SophiaMissileTailUp,
	SophiaMissileTailRight,
	SophiaMissileTailDown,
	SophiaHealthBar,
#pragma endregion
#pragma region Jason
	JasonWalkLeft1,
	JasonWalkLeft2,
	JasonWalkLeft3,
	JasonWalkLeft4,
	JasonWalkRight1,
	JasonWalkRight2,
	JasonWalkRight3,
	JasonWalkRight4,
	JasonWalkClimb1,
	JasonWalkClimb2,
	JasonWalkCrawlLeft1,
	JasonWalkCrawlLeft2,
	JasonWalkCrawlRight1,
	JasonWalkCrawlRight2,
	JasonFall1,
	JasonFall2,
	JasonBullet,
	JasonTopDownWalkDown1,
	JasonTopDownWalkDown2,
	JasonTopDownWalkDown3,
	JasonTopDownWalkLeft1,
	JasonTopDownWalkLeft2,
	JasonTopDownWalkLeft3,
	JasonTopDownWalkUp1,
	JasonTopDownWalkUp2,
	JasonTopDownWalkUp3,
	JasonTopDownWalkRight1,
	JasonTopDownWalkRight2,
	JasonTopDownWalkRight3,
	JasonTopDownBulletLeft,
	JasonTopDownBulletUp,
	JasonTopDownBulletRight,
	JasonTopDownBulletDown,
	JasonHealthBar,
#pragma endregion
	PlayerUpgrade,
	TextPow,
	TextHov,
	HealthBall,
	EnergyBall,
	PowerBall,
	FireBall,
	Explosion1,
	Explosion2,
	Explosion3,
	Explosion4,
#pragma region Worm
	WormMoveLeft1,
	WormMoveLeft2,
	WormMoveRight1,
	WormMoveRight2,
#pragma endregion
#pragma region Dome
	DomeUpMoveLeft1,
	DomeUpMoveLeft2,
	DomeUpMoveRight1,
	DomeUpMoveRight2,
	DomeDownMoveLeft1,
	DomeDownMoveLeft2,
	DomeDownMoveRight1,
	DomeDownMoveRight2,
	DomeLeftMoveUp1,
	DomeLeftMoveUp2,
	DomeLeftMoveDown1,
	DomeLeftMoveDown2,
	DomeRightMoveUp1,
	DomeRightMoveUp2,
	DomeRightMoveDown1,
	DomeRightMoveDown2,
#pragma endregion
#pragma region Jumper
	JumperMoveLeft1,
	JumperMoveLeft2,
	JumperMoveLeft3,
	JumperMoveRight1,
	JumperMoveRight2,
	JumperMoveRight3,
#pragma endregion
#pragma region Orb
	Orb1,
	Orb2,
	Orb3,
	Orb4,
	Orb5,
#pragma endregion
#pragma region Walker
	Walker1,
	Walker2,
	Walker3,
	Walker4,
#pragma endregion
#pragma region Skull
	SkullMoveLeft1,
	SkullMoveLeft2,
	SkullMoveRight1,
	SkullMoveRight2,
	SkullBullet,
#pragma endregion
#pragma region Floater
	FloaterMove1,
	FloaterMove2,
#pragma endregion
#pragma region Insect
	InsectMoveLeft1,
	InsectMoveLeft2,
	InsectMoveRight1,
	InsectMoveRight2,
#pragma endregion
#pragma region Insect
	DasherIdle1,
	DasherIdle2,
	DasherIdle3,
	DasherIdle4,
	DasherMove1,
	DasherMove2,
	DasherMove3,
	DasherMove4,
#pragma endregion
#pragma region Head
	HeadLeft1,
	HeadLeft2,
	HeadRight1,
	HeadRight2,
#pragma endregion
#pragma region Spiral
	SpiralLeft1,
	SpiralLeft2,
	SpiralRight1,
	SpiralRight2,
#pragma endregion
#pragma region Teleporter
	TeleporterLeft1,
	TeleporterLeft2,
	TeleporterRight1,
	TeleporterRight2,
#pragma endregion
#pragma region Eyeball
	Eyeball1,
	Eyeball2,
	Eyeball3,
#pragma endregion
#pragma region canon
	Canon1,
	Canon2,
	Canon3,
#pragma endregion
#pragma region boss
	BossHead1,
	BossHead2,
	BossHead3,
	BossHead4,
	BossHead5,
	BossHead6,
	BossHead7,
	BossHead8,
	BossLeftArm,
	BossLeftHand,
	BossRightArm,
	BossRightHand,
#pragma endregion
#pragma region Enemy bullet
	MineBullet,
	EnemySideScrollBullet1,
	EnemySideScrollBullet2,
	EnemyTopDownBullet1,
	EnemyTopDownBullet2,
#pragma endregion
#pragma region Portal
	PortalRight1,
	PortalRight2,
	PortalLeft1,
	PortalLeft2,
#pragma endregion
#pragma region Opening
	Opening1,
	Opening2,
	Opening3,
	Opening4,
	Opening5,
	Opening6,
	Opening7,
	Opening8,
	Opening9,
	Opening10,
	Opening11,
	Opening12,
	Opening13,
	Opening14,
	Opening15,
	Opening16,
	Opening17,
	Opening18,
	Opening19,
	Opening20,
	Opening21,
	Opening22,
	Opening23,
	Opening24,
	Opening25,
	Opening26,
	Opening27,
	Opening28,
	Opening29,
	Opening30,
	Opening31,
	Opening32,
	Opening33,
	Opening34,
	Opening35,
	Opening36,
	Opening37,
#pragma endregion
#pragma region Rollout
	Rollout1,
	Rollout2,
	Rollout3,
	Rollout4,
	Rollout5,
	Rollout6,
	Rollout7,
	Rollout8,
	Rollout9,
	Rollout10,
#pragma endregion
#pragma region Other
	BreakableWall,
	BlackScreen,
#pragma endregion
	COUNT // Special enum
};

} // namespace ids