# This is a basic workflow to help you get started with Actions

name: builds

on: [push, workflow_dispatch]
jobs:
  debug-build:
    runs-on: windows-latest

    steps:
      - uses: ./.github/actions/build-action
        with:
          config: "Debug Win64"
          
  profile-build:
    runs-on: windows-latest

    steps:
      - uses: ./.github/actions/build-action
        with:
          config: "Profile Win64"
          
  release-build:
    runs-on: windows-latest

    steps:
      - uses: ./.github/actions/build-action
        with:
          config: "Release Win64"
          
