name: build-all

on: [push, workflow_dispatch]
jobs:
  all-builds:
    strategy:
      matrix: 
        configs: [Debug Win64, Profile Win64, Release Win64]

    uses: ./.github/workflows/build.yml
    with:
      config: ${{ matrix.configs }}
         