# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"
