# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
jobs:
  prepare:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate projects
        run: |
          cd ${{github.workspace}}/code/prj
            call gen_prj_2019.bat
        shell: cmd

      - name: Build Debug
        run: |
          cd ${{github.workspace}}/code/prj/vs2019
            msbuild app.vcxproj -t:rebuild /p:Configuration="Debug Win64" /p:Platform=x64
        shell: cmd

      - name: Build Profile
        run: |
          cd ${{github.workspace}}/code/prj/vs2019
            msbuild app.vcxproj -t:rebuild /p:Configuration="Profile Win64" /p:Platform=x64
        shell: cmd

      - name: Build Release
        run: |
          cd ${{github.workspace}}/code/prj/vs2019
            msbuild app.vcxproj -t:rebuild /p:Configuration="Release Win64" /p:Platform=x64
        shell: cmd
