# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
jobs:
  Test-Debug:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"

      - name: Generate project 2019
        run: |
          pushd ./code/prj
            call 'gen_prj_2019.bat'
          popd

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Debug project 2019
        run: |
          pushd ./code/prj/vs2019
            call 'msbuild Game.sln -t:rebuild -verbosity:diag -property:Configuration=Debug'
          popd
          
