# This is a basic workflow to help you get started with Actions

name: builds

on: [push, workflow_dispatch]
jobs:
  debug-build:
    runs-on: windows-latest

    strategy:
      matrix: 
        configs: [Debug Win64, Profile Win64, Release Win64]

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/build-action
        with:
          config: ${{ matrix.configs }}
          
  profile-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/build-action
        with:
          config: Profile Win64
          
  release-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/build-action
        with:
          config: Release Win64
          
