# This is a basic workflow to help you get started with Actions

name: CI

on: [push, workflow_dispatch]
jobs:
  test-build:
    runs-on: windows-2019

    strategy:
      matrix:
        configuration: [
          "Debug Win64",
          "Profile Win64",
          "Release Win64"
        ]

    steps:
      - uses: actions/checkout@v3

      - uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"

      - uses: microsoft/setup-msbuild@v1.1

      - name: Generate project 2019
        run: |
          cd ${{github.workspace}}/code/prj
            call gen_prj_2019.bat
        shell: cmd

      - name: Build Debug project 2019
        run: |
          cd ${{github.workspace}}/code/prj/vs2019
            msbuild app.vcxproj -t:rebuild /p:Configuration=$ {{matrix.configuration}} /p:Platform=x64
        shell: cmd
          
