name: build-all

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix: 
        configs: [Debug Win64, Profile Win64, Release Win64]

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/build-action
        with:
          config: ${{ matrix.configs }}
          
