# This is a basic workflow to help you get started with Actions

name: build

on: [push, workflow_dispatch]
jobs:
  set-configs:
    runs-on: windows-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=matrix:: 
          {
            \"include\": 
              [
                {
                  \"config\":\"Debug\"
                },
                {
                  \"config\":\"Profile\"
                }, 
                {
                  \"config\":\"Release\"
                }
              ]
          }"
      shell: cmd

  test-build:
    needs: set-configs
    runs-on: windows-latest

    strategy:
      matrix: ${{fromJson(needs.set-configs.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      - uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"

      - uses: microsoft/setup-msbuild@v1.1

      - name: Generate project vs2019
        run: |
          cd ${{github.workspace}}/code/prj
            call gen_prj_2019.bat
        shell: cmd

      - run: |
          cd ${{github.workspace}}/code/prj/vs2019
            msbuild app.vcxproj -t:rebuild /p:Configuration=$ {{matrix.config}} /p:Platform=x64
        shell: cmd
          
