# This is a basic workflow to help you get started with Actions

name: CI

on: [push]
jobs:
  Test-Debug:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate project 2019
        run: |
          cd ${{github.workspace}}/code/prj
            call gen_prj_2019.bat
        shell: cmd

      - name: Build Debug project 2019
        run: |
          cd ${{github.workspace}}/code/prj/vs2019
            msbuild app.vcxproj -t:rebuild -property:Configuration=Debug
        shell: cmd
          
